-- ============================================================================
-- E-Wallet — Oracle Schema (DDL only)
-- Create order: wallets -> wallet_balances/cards/transaction_codes
--               account_types -> accounts
--               transaction_types / transaction_status -> transactions
--               atms
-- Run seed-data.sql afterwards to populate lookup tables, ATMs and their
-- type-3 (ATM) accounts.
-- Note: wallets.status defaults to 0 (inactive) — a new wallet stays locked
-- until its owner enters the 6-digit WhatsApp activation code stored in
-- otp_codes, then status flips to 1.
-- ============================================================================

CREATE TABLE wallets(
	wallet_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	phone_number VARCHAR2(11) NOT NULL,
	national_id VARCHAR2(14) NOT NULL,
	full_name VARCHAR2(50) NOT NULL,
	pin_hash VARCHAR2(250) NOT NULL,
	salt VARCHAR2(250) NOT NULL,
	status NUMBER DEFAULT(0),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP,

	CONSTRAINT PK_WALLETS PRIMARY KEY (wallet_id),
	CONSTRAINT CHECK_PHONE_NUMBER_LENGTH CHECK (REGEXP_LIKE(phone_number, '^[0-9]{11}$')),
	CONSTRAINT CHECK_NATIONAL_ID_LENGTH CHECK (REGEXP_LIKE(national_id, '^[0-9]{14}$')),
	CONSTRAINT UQ_PHONE UNIQUE(phone_number),
	CONSTRAINT CHECK_WALLET_STATUS CHECK(status IN (0,1))

);

CREATE TABLE otp_codes(
	code_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	wallet_id NUMBER NOT NULL,
	code VARCHAR2(6) NOT NULL,
	purpose VARCHAR2(10) DEFAULT 'ACTIVATION' NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	expires_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL '10' MINUTE),
	attempts NUMBER DEFAULT(0),
	is_used NUMBER default(0),
	is_Expire NUMBER default(0),
	CONSTRAINT PK_OTP_CODES PRIMARY KEY (code_id),
	CONSTRAINT FK_OTP_WALLET_ID FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id),
	CONSTRAINT CH_OTP_USED CHECK(is_used IN (0,1)),
	CONSTRAINT CH_OTP_EXPIRE CHECK(is_Expire IN (0,1)),
	CONSTRAINT UQ_OTP_WALLET_CODE UNIQUE (wallet_id, code),
	CONSTRAINT CK_OTP_ATTEMPTS CHECK(attempts BETWEEN 0 AND 3),
	CONSTRAINT CH_OTP_CODE_LENGTH CHECK(REGEXP_LIKE(code,'^[0-9]{6}$')),
	CONSTRAINT CH_OTP_PURPOSE CHECK(purpose IN ('ACTIVATION','RESET'))
);

CREATE TABLE wallet_balances(
	wallet_id NUMBER,
	available_balance NUMBER(12,2) DEFAULT(0),
	held_balance NUMBER(12,2) DEFAULT(0),
	updated_at TIMESTAMP,

	CONSTRAINT PK_WALLET_BALANCES PRIMARY KEY (wallet_id),
	CONSTRAINT FK_WALLET_BALANCE_ID FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id)

);

CREATE TABLE cards(
	card_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	wallet_id NUMBER NOT NULL,
	card_number VARCHAR2(16) NOT NULL,
	card_name VARCHAR2(100),
	card_holder_name VARCHAR2(100),
	bank_name VARCHAR2(100),
	expire_date DATE NOT NULL,
	cvv VARCHAR2(3) NOT NULL,
	status NUMBER DEFAULT 1,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


	CONSTRAINT PK_CARDS PRIMARY KEY (card_id),
	CONSTRAINT FK_CARDS_WALLET_ID FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id),
	CONSTRAINT CHECK_CARD_NUMBER_LENGTH CHECK (REGEXP_LIKE(card_number, '^[0-9]{16}$')),
	CONSTRAINT CHECK_CVV_LENGTH CHECK (REGEXP_LIKE(cvv, '^[0-9]{3}$')),
	CONSTRAINT UQ_CARD_NUMBER_WALLET UNIQUE(wallet_id,card_number)
);


CREATE TABLE atms(
	atm_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	atm_name VARCHAR2(100) NOT NULL,
	atm_location VARCHAR2(100) NOT NULL,
	status NUMBER DEFAULT(1),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	mapX NUMBER NOT NULL,
	mapY NUMBER NOT NULL,

	CONSTRAINT PK_ATMS PRIMARY KEY (atm_id),
	CONSTRAINT CHECK_ATM_STATUS CHECK(status IN (0,1))

);

CREATE TABLE account_types(
	account_type_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	type_name  VARCHAR2(100) NOT NULL,

	CONSTRAINT PK_ACCOUNT_TYPES PRIMARY KEY (account_type_id),
	CONSTRAINT UQ_ACCOUNT_TYPE_NAME UNIQUE(type_name)

);

CREATE TABLE accounts(
	account_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	account_type_id NUMBER NOT NULL,
	reference_id NUMBER NOT NULL,
	status NUMBER DEFAULT 1,

	CONSTRAINT PK_ACCOUNTS PRIMARY KEY (account_id),
	CONSTRAINT FK_ACCOUNT_TYPE_ID FOREIGN KEY (account_type_id) REFERENCES account_types(account_type_id),
	CONSTRAINT UQ_ACCOUNT_TYPE_REFRENCE_ID UNIQUE (account_type_id, reference_id)
);


CREATE TABLE transaction_types(
	transaction_type_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	type_name  VARCHAR2(100) NOT NULL,

	CONSTRAINT PK_TRANSACTION_TYPES PRIMARY KEY (transaction_type_id),
	CONSTRAINT UQ_TRANSACTION_TYPE_NAME UNIQUE(type_name)

);

CREATE TABLE transaction_status(
	transaction_status_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	status_name  VARCHAR2(100) NOT NULL,

	CONSTRAINT PK_TRANSACTION_STATUS PRIMARY KEY (transaction_status_id),
	CONSTRAINT UQ_TRANSACTION_STATUS_NAME UNIQUE(status_name)

);

CREATE TABLE transactions(
	transaction_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	from_account_id NUMBER NOT NULL,
	to_account_id NUMBER NOT NULL,
	transaction_type_id NUMBER NOT NULL,
	transaction_status_id NUMBER NOT NULL,
	amount NUMBER(12,2) NOT NULL,
	fees NUMBER(12,2) DEFAULT(0),
	reference_number VARCHAR2(50) NOT NULL,
	description VARCHAR2(500),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP,

	CONSTRAINT PK_TRANSACTIONS PRIMARY KEY (transaction_id),
	CONSTRAINT FK_FROM_ACCOUNT_ID FOREIGN KEY (from_account_id) REFERENCES accounts(account_id),
	CONSTRAINT FK_TO_ACCOUNT_ID FOREIGN KEY (to_account_id) REFERENCES accounts(account_id),
	CONSTRAINT FK_TRANSACTION_TYPE_ID FOREIGN KEY (transaction_type_id) REFERENCES transaction_types(transaction_type_id),
	CONSTRAINT FK_TRANSACTION_STATUS_ID FOREIGN KEY (transaction_status_id) REFERENCES transaction_status(transaction_status_id)

);

CREATE TABLE transaction_codes(
	code_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	wallet_id NUMBER NOT NULL,
	code VARCHAR2(9) NOT NULL,
	amount NUMBER(12,2) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	expires_at TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL '10' MINUTE),
	attempts NUMBER DEFAULT(0),
	is_used NUMBER default(0),
	is_Expire NUMBER default(0),
	CONSTRAINT PK_TRANSACTIONS_CODES PRIMARY KEY (code_id),
	CONSTRAINT FK_TRANSACTIONS_CODE_WALLET_ID FOREIGN KEY (wallet_id) REFERENCES wallets(wallet_id),
	CONSTRAINT CH_IS_USED CHECK(is_used IN (0,1)),
	CONSTRAINT CH_IS_EXPIER CHECK(is_Expire IN (0,1)),
	CONSTRAINT UQ_WALLET_CODE UNIQUE (wallet_id, code),
	CONSTRAINT CK_ATTEMPTS CHECK(attempts BETWEEN 0 AND 3),
	CONSTRAINT CH_CODE_LENGTH CHECK(REGEXP_LIKE(code,'^[0-9]{6,9}$'))

);



CREATE INDEX IDX_TRANSACTION_CREATED
ON TRANSACTIONS(created_at);

CREATE INDEX IDX_TRANSACTION_FROM
ON TRANSACTIONS(from_account_id);

CREATE INDEX IDX_TRANSACTION_TO
ON TRANSACTIONS(to_account_id);



CREATE INDEX IDX_OTP_WALLET
ON OTP_CODES(wallet_id);

CREATE INDEX IDX_CODES_WALLET
ON TRANSACTION_CODES(wallet_id);